# Generated by Django 5.0 on 2025-12-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('full-stack development', 'Full-Stack Development'), ('data visualization', 'Data Visualization'), ('saas application', 'SaaS Application'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.JSONField(blank=True, default=list, help_text='List of challenges faced (array of strings)'),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateField(blank=True, help_text='Alternative date field', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, help_text='Project completion or launch date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs'),
        ),
        migrations.AddField(
            model_name='project',
            name='learnings',
            field=models.JSONField(blank=True, default=list, help_text='List of key learnings (array of strings)'),
        ),
        migrations.AddField(
            model_name='project',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text="Array of media objects with 'type', 'src', 'alt'"),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.JSONField(blank=True, default=list, help_text='List of solutions implemented (array of strings)'),
        ),
        migrations.AddField(
            model_name='project',
            name='videos',
            field=models.JSONField(blank=True, default=list, help_text='Array of video URLs'),
        ),
    ]
