# Generated by Django 5.0 on 2025-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_app', '0002_project_category_project_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed description for the About Me section'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Short intro for the Home/Hero section'),
        ),
    ]
